### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chisaipete** [dobrakmato/python-import-inliner#2]
I'd like to use this code, or at least modify it for my purpose, but it needs to have a License, otherwise strict copyright laws are enforced as per explanation here: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by chisaipete** [comment]
https://choosealicense.com/licenses/mit/# 

Perhaps?

**Comment by dobrakmato** [comment]
Hello, I added MIT license in 143092e1e2ee0e8288632777943dc543c5f817db. Hope it suits your needs!
